# Generated by Django 4.1 on 2023-01-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='plataformasAceptadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PM', 'PagoMovil'), ('ZE', 'Zelle'), ('AT', 'Airtm')], default='PM', max_length=2)),
                ('descripcion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='preguntasSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeUsuariodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIL', 'Psicólogo'), ('PAC', 'Paciente')], default='PAC', max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cedula', models.IntegerField(default=0, verbose_name='Cédula')),
                ('telefono', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('correo', models.CharField(default='sample@gmail.com', max_length=50, verbose_name='Correo')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('ubicacion', models.CharField(max_length=10, verbose_name='Ubicación')),
                ('passActual', models.CharField(default=12345, max_length=20, verbose_name='Contraseña')),
                ('citas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.citas')),
                ('tipoDeUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.tipodeusuariodos', verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='piscologoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=15)),
                ('duracionTerapia', models.IntegerField(default=1)),
                ('IDplataformas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.plataformasaceptadas')),
                ('IDusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='historiaContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passAntiguo', models.CharField(max_length=20)),
                ('passActual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.usuario')),
                ('preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.preguntasseguridad')),
            ],
        ),
        migrations.AddField(
            model_name='citas',
            name='tipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.tipodeusuariodos'),
        ),
    ]
