# Generated by Django 4.1 on 2022-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0003_alter_citas_fechacita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fechaCita',
            field=models.DateTimeField(),
        ),
    ]
