# Generated by Django 4.1 on 2023-01-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0003_alter_piscologopublicacion_duracionterapia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diasDisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], default='LU', max_length=2)),
            ],
        ),
    ]
