# Generated by Django 4.1 on 2022-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0004_alter_citas_fechacita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodeusuario',
            old_name='nombre',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
    ]
