# Generated by Django 4.1 on 2023-01-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0006_remove_diasdisp_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piscologopublicacion',
            name='dias',
        ),
        migrations.DeleteModel(
            name='diasDisp',
        ),
    ]
