# Generated by Django 4.1 on 2023-01-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0007_rename_passuser_historiacontrasena_passactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(default=0, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='passActual',
            field=models.CharField(default=12345, max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDeUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.tipodeusuario', verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(max_length=10, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
    ]
