# Generated by Django 4.1 on 2023-01-31 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TEG', '0007_remove_piscologopublicacion_dias_delete_diasdisp'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(default=0, verbose_name='Cédula')),
                ('telefono', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('ubicacion', models.CharField(max_length=10, verbose_name='Ubicación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='historiacontrasena',
            name='passActual',
        ),
        migrations.RemoveField(
            model_name='historiacontrasena',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='citas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipoDeUsuario',
        ),
        migrations.DeleteModel(
            name='citas',
        ),
        migrations.DeleteModel(
            name='historiaContrasena',
        ),
        migrations.DeleteModel(
            name='TipoDeUsuariodos',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AlterField(
            model_name='piscologopublicacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.usuarioinfo'),
        ),
    ]
