# Generated by Django 4.1 on 2023-01-31 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TEG', '0008_usuarioinfo_remove_historiacontrasena_passactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscologopublicacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
