# Generated by Django 4.1 on 2022-10-08 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateTimeField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='historiaContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passActual', models.CharField(max_length=20)),
                ('passAntiguo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='plataformasAceptadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PM', 'PagoMovil'), ('ZE', 'Zelle'), ('AT', 'Airtm')], default='PM', max_length=2)),
                ('descripcion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='preguntasSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PSI', 'Psicólogo'), ('PAC', 'Paciente')], default='PAC', max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('cedula', models.IntegerField(default=0, max_length=8)),
                ('telefono', models.IntegerField(default=0, max_length=8)),
                ('correo', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=10)),
                ('citas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.citas')),
                ('passUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.historiacontrasena')),
                ('tipoDeUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.tipodeusuario')),
            ],
        ),
        migrations.CreateModel(
            name='piscologoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=15, max_length=10)),
                ('duracionTerapia', models.IntegerField(default=1, max_length=10)),
                ('IDplataformas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.plataformasaceptadas')),
                ('IDusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='historiacontrasena',
            name='preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.preguntasseguridad'),
        ),
        migrations.AddField(
            model_name='citas',
            name='tipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEG.tipodeusuario'),
        ),
    ]
