# Generated by Django 4.1 on 2022-12-12 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0002_alter_piscologopublicacion_duracionterapia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fechaCita',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
