# Generated by Django 4.1 on 2022-12-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0006_remove_historiacontrasena_passactual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiacontrasena',
            old_name='passUser',
            new_name='passActual',
        ),
    ]
