# Generated by Django 4.1 on 2023-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0010_remove_usuario_email_remove_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(verbose_name='Fecha de nacimiento'),
        ),
    ]
