# Generated by Django 4.1 on 2023-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0011_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(default='202-12-05', verbose_name='Fecha de nacimiento'),
        ),
    ]
