# Generated by Django 4.1 on 2023-01-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEG', '0012_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechaNacimiento',
        ),
    ]
